meta-voyager: wic: Fix vbmeta boot issues
The patch introducing secureboot support was not booting,
because AVB of failing to verify the vbmeta header:

  avb_vbmeta_image.c:65: ERROR: Magic is incorrect.
  avb_slot_verify.c:772: ERROR: vbmeta_a:
    Error verifying vbmeta image: invalid vbmeta header

The issue is that the actual generated image was never copied to the
vbmeta_a and vbmeta_b partitions.

Fix this by copying the generated vbmeta image to the correct slots.

Fixes: 555630510cc ("meta-axelera: Add Secureboot support for Android bootflow")
YouTrack-Id: AXELERA-207
Change-Id: Ibcdcd587a59dbbd7488c61b5b670742672901d29
Signed-off-by: Patrick Barsanti <patrick.barsanti@amarulasolutions.com>