kas: Add meta-xfce layer and missing dependences
ERROR: Nothing RPROVIDES 'xfce4-terminal'
(but /build/../repo/meta-axelera/meta-voyager/recipes-core/images/voyager-image-weston.bb
RDEPENDS on or otherwise requires it)

Fixes: ba2d88391dc3 ("voyager-image-weston: Add xfce4-terminal")
YouTrack-Id: AXELERA-67
Change-Id: I9ac907b1efd815379e3df154bc0e7501e9687572
Signed-off-by: Patrick Barsanti <patrick.barsanti@amarulasolutions.com>
Signed-off-by: Michael Trimarchi <michael@amarulasolutions.com>