kas/include/base.yaml: Missing include definition of LOCAL_VERSION
The LOCAL_VERSION should corrispond at least to the sample local version and in case of kirstone
it's 2

ERROR: voyager-image-weston-1.0-r0 do_populate_sdk_ext: Failed to generate filtered task list for extensible SDK:

You can now run 'bitbake <target>'

Common targets are:
    core-image-minimal
    core-image-full-cmdline
    core-image-sato
    core-image-weston
    meta-toolchain
    meta-ide-support

You can also run generated qemu images with a command like 'runqemu qemux86-64'.

Other commonly useful commands are:
 - 'devtool' and 'recipetool' handle common recipe tasks
 - 'bitbake-layers' handles common layer tasks
 - 'oe-pkgdata-util' handles common target package tasks
ERROR: bitbake failed:
ERROR: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:oecore_update_localconf(d)
     0003:
File: '/work/build/tmp-glibc/work/antelao_3588-voyager-linux/voyager-image-weston/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/meta/classes/sanity.bbclass', lineno: 56, function: oecore_update_localconf
     0052:
     0053:is a good way to visualise the changes."""
     0054:    failmsg = d.expand(failmsg)
     0055:
 *** 0056:    raise NotImplementedError(failmsg)
     0057:}
     0058:
     0059:SANITY_SITECONF_SAMPLE ?= "${COREBASE}/meta*/conf/site.conf.sample"
     0060:python oecore_update_siteconf() {
Exception: NotImplementedError: Your version of local.conf was generated from an older/newer version of
local.conf.sample and there have been updates made to this file. Please compare the two
files and merge any changes before continuing.

Matching the version numbers will remove this message.

"meld conf/local.conf /work/build/tmp-glibc/work/antelao_3588-voyager-linux/voyager-image-weston/1.0-r0/sdk-ext/image/tmp-renamed-sdk/layers/openembedded-core/meta*/conf/local.conf.sample"

is a good way to visualise the changes.
ERROR: Logfile of failure stored in: /work/build/tmp-glibc/work/antelao_3588-voyager-linux/voyager-image-weston/1.0-r0/temp/log.do_populate_sdk_ext.79320
ERROR: Task (/work/build/../../repo/meta-axelera/meta-voyager/recipes-core/images/voyager-image-weston.bb:do_populate_sdk_ext) failed with exit code '1'

Change-Id: Ica5269781acbb0720db2aa761b71ecd57d337ee3
Signed-off-by: Michael Trimarchi <michael@amarulasolutions.com>